name: Build ZMK firmware
on:
  push:
    paths-ignore:
      - 'hardware/**'
      - 'case/**'
      - 'images/**'
      - 'README.md'
      - 'bootloader/**'
  pull_request:
    paths-ignore:
      - 'hardware/**'
      - 'case/**'
      - 'images/**'
      - 'README.md'
      - 'bootloader/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
